version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ~/.m2:/root/.m2  # 挂载本地 Maven 仓库

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    volumes:
      - ~/.m2:/root/.m2

  service-provider:
    build: ./service-provider
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    volumes:
      - ~/.m2:/root/.m2

  service-consumer:
    build: ./service-consumer
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    volumes:
      - ~/.m2:/root/.m2
