# service-provider-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-provider
  template:
    metadata:
      labels:
        app: service-provider
    spec:
      containers:
        - name: service-provider
          image: service-provider:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka"
---
# service-provider-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-provider
spec:
  selector:
    app: service-provider
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
