server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-provider-route
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1  # 移除 /provider 前缀
            - AddRequestHeader=X-Request-Id, 1234

        - id: service-consumer-route
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
