# service-consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-consumer
  template:
    metadata:
      labels:
        app: service-consumer
    spec:
      containers:
        - name: service-consumer
          image: service-consumer:latest
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka"
---
# service-consumer-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-consumer
spec:
  selector:
    app: service-consumer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
